<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ormannotations"
    nsURI="http://www.eclipse.org/emf/texo/orm/ormannotations" nsPrefix="ormannotations">
  <eClassifiers xsi:type="ecore:EClass" name="EPackageORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EPackageAnnotation #//ENamedElementORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateFullDbSchemaNames"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameDictionaryPropertyFile"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableNamePrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnNamePrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumSqlNameLength" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="255"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerCasedNames" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperCasedNames" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enforceUniqueNames" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useJoinTablesForContainment"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useJoinTablesForNonContainment"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCascadeContainment"
        eType="ecore:EClass orm.ecore#//CascadeType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCascadeNonContainment"
        eType="ecore:EClass orm.ecore#//CascadeType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityMappings" eType="ecore:EClass orm.ecore#//EntityMappingsType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateJavaAnnotations"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addOrderColumnToListMappings"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renameSQLReservedNames"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritance" eType="ecore:EClass orm.ecore#//Inheritance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeElementORMAnnotation" abstract="true"
      interface="true" eSuperTypes="#//ENamedElementORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transient" eType="ecore:EClass orm.ecore#//Transient"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassifierORMAnnotation" abstract="true"
      interface="true" eSuperTypes="#//ETypeElementORMAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClassORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EClassAnnotation #//EClassifierORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass orm.ecore#//Entity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddable" eType="ecore:EClass orm.ecore#//Embeddable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedSuperclass" eType="ecore:EClass orm.ecore#//MappedSuperclass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritance" eType="ecore:EClass orm.ecore#//Inheritance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataTypeORMAnnotationDefinition" abstract="true"
      interface="true" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EDataTypeAnnotation #//EClassifierORMAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureORMAnnotation" abstract="true"
      interface="true" eSuperTypes="#//ETypeElementORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionTable" eType="ecore:EClass orm.ecore#//CollectionTable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementCollection" eType="ecore:EClass orm.ecore#//ElementCollection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EAttributeAnnotation #//EStructuralFeatureORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basic" eType="ecore:EClass orm.ecore#//Basic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass orm.ecore#//Id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass orm.ecore#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oneToMany" eType="ecore:EClass orm.ecore#//OneToMany"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntity" eType="ecore:EClass orm.ecore#//Entity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manyToOne" eType="ecore:EClass orm.ecore#//ManyToOne"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EReferenceAnnotation #//EStructuralFeatureORMAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="embedded" eType="ecore:EClass orm.ecore#//Embedded"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedId" eType="ecore:EClass orm.ecore#//EmbeddedId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinColumn" upperBound="-1"
        eType="ecore:EClass orm.ecore#//JoinColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinTable" eType="ecore:EClass orm.ecore#//JoinTable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manyToMany" eType="ecore:EClass orm.ecore#//ManyToMany"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manyToOne" eType="ecore:EClass orm.ecore#//ManyToOne"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oneToMany" eType="ecore:EClass orm.ecore#//OneToMany"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oneToOne" eType="ecore:EClass orm.ecore#//OneToOne"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKey" eType="ecore:EClass orm.ecore#//MapKey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyClass" eType="ecore:EClass orm.ecore#//MapKeyClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyColumn" eType="ecore:EClass orm.ecore#//MapKeyColumn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyJoinColumn" upperBound="-1"
        eType="ecore:EClass orm.ecore#//MapKeyJoinColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderBy" eType="ecore:EDataType orm.ecore#//OrderBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderColumn" eType="ecore:EClass orm.ecore#//OrderColumn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicCollection" eType="ecore:EClass orm.ecore#//BasicCollection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicMap" eType="ecore:EClass orm.ecore#//BasicMap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationOverride" upperBound="-1"
        eType="ecore:EClass orm.ecore#//AssociationOverride" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOverride" upperBound="-1"
        eType="ecore:EClass orm.ecore#//AttributeOverride" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKeyJoinColumn" upperBound="-1"
        eType="ecore:EClass orm.ecore#//PrimaryKeyJoinColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnumORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EEnumAnnotation #//EDataTypeORMAnnotationDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerated" eType="ecore:EEnum orm.ecore#//Enumerated"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basic" eType="ecore:EClass orm.ecore#//Basic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass orm.ecore#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementCollection" eType="ecore:EClass orm.ecore#//ElementCollection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataTypeORMAnnotation" eSuperTypes="../../org.eclipse.emf.texo.annotations.model/model/texo-annotations-model.ecore#//EDataTypeAnnotation #//EDataTypeORMAnnotationDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basic" eType="ecore:EClass orm.ecore#//Basic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass orm.ecore#//Id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass orm.ecore#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementCollection" eType="ecore:EClass orm.ecore#//ElementCollection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENamedElementORMAnnotation" abstract="true"
      interface="true"/>
</ecore:EPackage>
