<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz306546" nsURI="http://www.eclipse.org/emf/texo/test/model/issues/instanceclassset"
    nsPrefix="bz306546">
  <eClassifiers xsi:type="ecore:EClass" name="Serializable" instanceClassName="java.io.Serializable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MySerializableClass" eSuperTypes="http://www.eclipse.org/emf/texo/test/model/base/identifiable#//Identifiable #//Serializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="somethingInteresting" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="somethingInteresting"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonEMF" eType="#//NonEMF"
        transient="true">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="nonEMF"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonEMFs" upperBound="-1"
        eType="#//NonEMF" transient="true">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="nonEMFs"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonEMF" instanceClassName="org.eclipse.emf.texo.test.model.instanceclassset.NonEMF"
      eSuperTypes="http://www.eclipse.org/emf/texo/test/model/base/identifiable#//Identifiable"/>
</ecore:EPackage>
