<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz403161_2" nsURI="http://www.eclipse.org/emf/texo/test/model/issues/bz403161_2"
    nsPrefix="bz403161_2">
  <eClassifiers xsi:type="ecore:EClass" name="Test403161_2" eSuperTypes="bz403161_1.ecore#//Test403161_1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
